<?php
/**
 * flavor-child — Functions
 *
 * Minimal setup for a sustainability site with pages and blog.
 * No sidebar, no bloat.
 */

// ── Enqueue Styles & Scripts ──────────────────────────────────────────────

add_action('wp_enqueue_scripts', function () {
    // Parent theme stylesheet.
    wp_enqueue_style(
        'flavor-parent',
        get_template_directory_uri() . '/style.css'
    );

    // Child theme stylesheet (style.css — header only, loads first).
    wp_enqueue_style(
        'flavor-child',
        get_stylesheet_uri(),
        ['flavor-parent']
    );

    // Custom stylesheet — all visual design lives here.
    wp_enqueue_style(
        'flavor-child-custom',
        get_stylesheet_directory_uri() . '/custom.css',
        ['flavor-child'],
        '1.0.0'
    );

    // Custom JS — lightweight, deferred.
    wp_enqueue_script(
        'flavor-child-custom',
        get_stylesheet_directory_uri() . '/custom.js',
        [],
        '1.0.0',
        true
    );
});

// ── Navigation ────────────────────────────────────────────────────────────

add_action('after_setup_theme', function () {
    register_nav_menus([
        'primary' => __('Primary Navigation', 'flavor-child'),
    ]);
});

// ── Custom Image Size ─────────────────────────────────────────────────────

add_action('after_setup_theme', function () {
    add_image_size('product-photo', 800, 600, true);
});

// ── Remove Bloat ──────────────────────────────────────────────────────────

// Emoji scripts and styles.
remove_action('wp_head', 'print_emoji_detection_script', 7);
remove_action('wp_print_styles', 'print_emoji_styles');
remove_action('admin_print_scripts', 'print_emoji_detection_script');
remove_action('admin_print_styles', 'print_emoji_styles');

// oEmbed / embed scripts.
remove_action('wp_head', 'wp_oembed_add_discovery_links');
remove_action('wp_head', 'wp_oembed_add_host_js');

// RSD, WLW manifest, shortlink, generator tag.
remove_action('wp_head', 'rsd_link');
remove_action('wp_head', 'wlmanifest_link');
remove_action('wp_head', 'wp_shortlink_wp_head');
remove_action('wp_head', 'wp_generator');

// REST API link in <head> (API still works, just not advertised).
remove_action('wp_head', 'rest_output_link_wp_head');

// Remove emoji DNS prefetch.
add_filter('emoji_svg_url', '__return_false');

// Remove jQuery Migrate on the front end (not needed for this site).
add_action('wp_default_scripts', function ($scripts) {
    if (!is_admin() && isset($scripts->registered['jquery'])) {
        $scripts->registered['jquery']->deps = array_diff(
            $scripts->registered['jquery']->deps,
            ['jquery-migrate']
        );
    }
});

// Remove Gutenberg block library CSS on the front end.
// Our pages use the block editor to author content, but we style
// everything ourselves in custom.css — the default block styles are dead weight.
add_action('wp_enqueue_scripts', function () {
    wp_dequeue_style('wp-block-library');
    wp_dequeue_style('wp-block-library-theme');
    wp_dequeue_style('wc-blocks-style');          // WooCommerce blocks (if ever installed)
    wp_dequeue_style('global-styles');             // Global styles generated by theme.json
    wp_dequeue_style('classic-theme-styles');      // Classic theme compat styles
}, 100);

// Remove wp-embed script (we don't embed external WordPress posts).
add_action('wp_footer', function () {
    wp_deregister_script('wp-embed');
});

// Prevent WordPress from loading Google Fonts or any external font.
// Our design uses system fonts (Helvetica, Georgia) — zero external requests.
add_filter('style_loader_src', function ($src) {
    if (strpos($src, 'fonts.googleapis.com') !== false) {
        return '';
    }
    return $src;
});

// Disable XML-RPC entirely (security — not needed for a static content site).
add_filter('xmlrpc_enabled', '__return_false');

// Remove the X-Pingback header that advertises XML-RPC.
add_filter('wp_headers', function ($headers) {
    unset($headers['X-Pingback']);
    return $headers;
});

// ── Hide Admin Bar for Non-Admins ─────────────────────────────────────────

add_filter('show_admin_bar', function () {
    return current_user_can('manage_options');
});

// ── Blog Support (Sustain Page) ───────────────────────────────────────────

// Custom excerpt length for the blog grid.
add_filter('excerpt_length', function () {
    return 25;
});

// Replace the default "[...]" with "..." for cleaner excerpts.
add_filter('excerpt_more', function () {
    return '&hellip;';
});

// ── Structured Data (JSON-LD) ────────────────────────────────────────────
// Outputs Organization and WebPage schema for better search engine results.
// Replace [your-domain.com] and [Your Name] with your actual values.

add_action('wp_head', function () {
    // Organization schema — appears on every page.
    $org = [
        '@context'    => 'https://schema.org',
        '@type'       => 'Organization',
        'name'        => get_bloginfo('name'),
        'url'         => home_url('/'),
        'description' => get_bloginfo('description'),
    ];
    echo '<script type="application/ld+json">' . wp_json_encode($org, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . '</script>' . "\n";

    // WebPage schema — specific to the current page.
    if (is_singular('page')) {
        $page = [
            '@context'    => 'https://schema.org',
            '@type'       => 'WebPage',
            'name'        => get_the_title(),
            'url'         => get_permalink(),
            'description' => get_the_excerpt() ?: wp_trim_words(get_the_content(), 30, '...'),
            'isPartOf'    => [
                '@type' => 'WebSite',
                'name'  => get_bloginfo('name'),
                'url'   => home_url('/'),
            ],
        ];
        echo '<script type="application/ld+json">' . wp_json_encode($page, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . '</script>' . "\n";
    }
}, 5);

// ── Analytics ────────────────────────────────────────────────────────────
// Uncomment ONE of the three options below. Do not use more than one.

// ─── OPTION A: Plausible Analytics (Recommended) ─────────────────────────
// Cookie-free, privacy-friendly, < 1KB script. No consent banner needed.
// Replace [your-domain.com] with your actual domain.
//
// add_action('wp_head', function () {
//     if (!current_user_can('manage_options')) {
//         echo '<script defer data-domain="[your-domain.com]" src="https://plausible.io/js/script.js"></script>' . "\n";
//     }
// }, 1);

// ─── OPTION A (alt): Fathom Analytics ────────────────────────────────────
// Also cookie-free and privacy-friendly. Replace [YOUR-SITE-ID] with
// the site ID from your Fathom dashboard.
//
// add_action('wp_head', function () {
//     if (!current_user_can('manage_options')) {
//         echo '<script src="https://cdn.usefathom.com/script.js" data-site="[YOUR-SITE-ID]" defer></script>' . "\n";
//     }
// }, 1);

// ─── OPTION B: Google Analytics 4 ────────────────────────────────────────
// Replace G-XXXXXXXXXX with your GA4 Measurement ID.
// NOTE: GA4 uses cookies — you WILL need a cookie consent notice for
// EU visitors (GDPR). See the cookie-notice section in custom.css.
//
// add_action('wp_head', function () {
//     if (!current_user_can('manage_options')) {
//         ?>
//         <!-- Google Analytics 4 -->
//         <!--
//         <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
//         <script>
//             window.dataLayer = window.dataLayer || [];
//             function gtag(){dataLayer.push(arguments);}
//             gtag('js', new Date());
//             gtag('consent', 'default', {
//                 'analytics_storage': 'denied'
//             });
//             gtag('config', 'G-XXXXXXXXXX', {
//                 send_page_view: true
//             });
//         </script>
//         -->
//         <?php
//     }
// }, 1);
